### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Kh3nsu** [IndrekHaav/photoprism-debian#11] opened 2023-02-01 18:22 UTC
Hello,

I have followed all the intructions in the tutorial. Except I have installed a newer Golang version (1.19.5).
Photoprism starts normally but I'm not able to access the Webinterface.
If I try to access the IP 192.168.30.3:2342 I get redirected to http://192.168.30.3:2342/library/login and get a "HTTP ERROR 500
This page cannot process your request right now".
I also get some weird initrd.img errors in the photoprism logs. I have attached it.
[photoprism.log](https://github.com/IndrekHaav/photoprism-debian/files/10560272/photoprism.log)

This is my .env:
```
PHOTOPRISM_AUTH_MODE="password"
PHOTOPRISM_ADMIN_PASSWORD="photoprism"
PHOTOPRISM_HTTP_HOST='0.0.0.0'
PHOTOPRISM_HTTP_PORT='2342'
PHOTOPRISM_DEBUG="true"

# PhotoPrism storage directories
PHOTOPRISM_STORAGE_PATH="/var/lib/photoprism"
PHOTOPRISM_ORIGINALS_PATH="/var/lib/photoprism/Originals"
PHOTOPRISM_IMPORT_PATH="/var/lib/photoprism/photos/Import"

# Uncomment below if using MariaDB/MySQL instead of SQLite (the default)
# PHOTOPRISM_DATABASE_DRIVER="mysql"
# PHOTOPRISM_DATABASE_SERVER="MYSQL_IP_HERE"
# PHOTOPRISM_DATABASE_NAME="DB_NAME"
# PHOTOPRISM_DATABASE_USER="USER_NAME"
# PHOTOPRISM_DATABASE_PASSWORD="PASSWORD"
```

**Comment by IndrekHaav** [comment] 2023-02-01 18:32
Any errors during the build process?

I found a similar discussion in PhotoPrism's Github: https://github.com/photoprism/photoprism/discussions/3042

It refers to this issue: https://github.com/photoprism/photoprism/issues/2946

There it is suggested that the error is caused by files in the root of the filesystem (directly under `/`). So that might be something to check.

**Comment by Kh3nsu** [comment] 2023-02-01 18:38
As far as I watched it, there were no errors when building at all.
I'm actually not quite sure what to look for? 
![image](https://user-images.githubusercontent.com/17033125/216132703-bae81023-b8f1-4757-86ba-d3321730ee40.png)

**Comment by IndrekHaav** [comment] 2023-02-01 19:44
Yeah, those files in the root of the filesystem might be the issue. Specifically, the "initrd" and "vmlinuz" files.

I found some info here that says they are symlinks to your current and previous kernel: https://askubuntu.com/q/1049427

You can confirm by running `ls -l`  while in the root directory; symlinks will have the letter "l" at the very beginning of the line (directories are marked with "d") and it will also show which files they link to.

Apparently you can delete the symlinks, but they can be recreated with a kernel update.

What OS are you running? Is this a fresh install or a used system? VM or physical machine?

The PhotoPrism issue I linked to before suggested that the bug is fixed in preview builds. So what you could try is going to the directory where you cloned the PhotoPrism source code and switching to the "preview" branch instead of "release", by running `git checkout preview`. Then go through all the subsequent install steps. If that doesn't fix it, you can also try the bleeding-edge "develop" branch.

**Comment by Kh3nsu** [comment] 2023-02-01 19:48
Thanks for the answer.
Here the requested information:
![image](https://user-images.githubusercontent.com/17033125/216147726-84b3a349-c5c3-4032-8116-74c3d9908e04.png)

I will try to install the preview branch and report back asap

**Comment by Kh3nsu** [comment] 2023-02-01 19:52
Also it is a VM and freshly installed. The only thing I did on this os was the tutorial from you

**Comment by Kh3nsu** [comment] 2023-02-01 19:53
I have now build photoprism with the preview branch and it does work now!
Using this build: 230201-b2ffa67e0

Thank you!

**Comment by IndrekHaav** [comment] 2023-02-01 20:30
Alright, good to hear you got it sorted.

I'll try and add a note about this to the troubleshooting section.

**Closed as completed** 2023-02-02 09:12 UTC
